<a href="https://colab.research.google.com/github/Ashwin-2408/Tensor_Flow_Learning/blob/main/notebooks/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
#creating a scalar tensor
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix=tf.constant([[1,2],[2,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 2, 10]], dtype=int32)>

In [ ]:
matrix.ndim


2

In [ ]:
#create another matrix
matrix2=tf.constant([[12],[12],[12]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 1), dtype=float16, numpy=
array([[12.],
       [12.],
       [12.]], dtype=float16)>

In [ ]:
#3 dimensional tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [20]:
#Lets create tensorflow Variables
var=tf.Variable([4,4])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 4], dtype=int32)>

Variable: The name of the variable. If you don't explicitly give it a name, TensorFlow auto-generates one.

0: Refers to the first output tensor of that variable (most variables only have one output, so it’s usually :0).

In [21]:
#reassigning the tensor variable using (.assign)
var[0].assign(9)
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 4], dtype=int32)>

In [22]:
var[0]=8

TypeError: 'ResourceVariable' object does not support item assignment

Assignment using direct indexing doensn't work we will have to use the (.assign()) function to reassign any values

**Note:**
We will rarely be deciding whether to use tf.constant or tf.variable,Tensorflow does this for us.However,if in doubt use tf.constant and can be changed later




---



## Creating Random Tensors


Random tensors are tensors of arbitrary size filled with random numbers



---
Creating a random constant tensor



In [29]:
random_tensor=tf.random.uniform(shape=[] ,minval=5, maxval=10)
random_tensor


<tf.Tensor: shape=(), dtype=float32, numpy=8.914843559265137>

We are using a uniform distribution

minval: lower bound (inclusive)

maxval: upper bound (exclusive)

In [33]:
random_vector=tf.random.uniform(shape=[2,2],dtype=tf.float16)
random_vector

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[0.3232, 0.2627],
       [0.825 , 0.7266]], dtype=float16)>


set_seed() function is used to reproduce the same sequence of numbers while generating random values

In [34]:
tf.random.set_seed(5)
vector=tf.random.normal(shape=[2,2])
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.18030666, -0.95028627],
       [-0.03964049, -0.7425406 ]], dtype=float32)>

In [37]:
tf.random.set_seed(5)
vector=tf.random.normal(shape=[2,2])
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.18030666, -0.95028627],
       [-0.03964049, -0.7425406 ]], dtype=float32)>

In [38]:
vector=tf.random.normal(shape=[2,2])
vector

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.22652864, 0.8106553 ],
       [0.7466094 , 0.7749703 ]], dtype=float32)>

In [50]:
g=tf.random.Generator.from_seed(5)
gen1=g.uniform(shape=[2,2])
saved_state = g.state.read_value()
gen2=g.uniform(shape=[2,2])
print(gen1)
print(gen2)
g.reset(saved_state)
gen3=g.uniform(shape=[2,2])
print(gen3)

tf.Tensor(
[[0.567016   0.2077086 ]
 [0.18223882 0.99883735]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.0657748  0.8750659 ]
 [0.60925746 0.4647795 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.0657748  0.8750659 ]
 [0.60925746 0.4647795 ]], shape=(2, 2), dtype=float32)


we get different values in gen1 and gen2 becasue the state has advanced

gen3 and gen2 have the same values because they are created from the same state