<a href="https://colab.research.google.com/github/Ashwin-2408/Tensor_Flow_Learning/blob/main/notebooks/TensorFlowBasics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Manipulating Tensors
Basics Operations:


*  +
*  -
*   *
*  /



In [2]:
import tensorflow as tf
A=tf.constant([2,2])

In [3]:
A+10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 12], dtype=int32)>

It does not change the original tensor

In [4]:
A


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

Use Tensorflow builtin functions to speed up operations while training

In [5]:
tf.multiply(A,4)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 8], dtype=int32)>

##Matrix Multiplication
Matrix multiplication is the most common operation in Machine Learning

In [6]:
A=tf.constant([[1,3]], shape=[1,2])
B=tf.constant([[2,4]],shape=[2,1])
A,B

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[2],
        [4]], dtype=int32)>)

The number of columns in the first tensor should be equal to the number of rows in the second tensor

In [7]:
tf.linalg.matmul(A,B)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [8]:
C=tf.constant([[1,2,3],[3,4,5],[5,6,5]])
C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 5]], dtype=int32)>

Element wise Multiplication

In [9]:
C*C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [ 9, 16, 25],
       [25, 36, 25]], dtype=int32)>

The '@' operator in python if for matrix multiplication

In [10]:
C@C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 28, 28],
       [40, 52, 54],
       [48, 64, 70]], dtype=int32)>

In [11]:
X=tf.random.uniform([2,3])
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.13778579, 0.29245162, 0.91041803],
       [0.25246203, 0.01176178, 0.641611  ]], dtype=float32)>

In [12]:
tf.transpose(X),tf.reshape(X,[3,2])

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.13778579, 0.25246203],
        [0.29245162, 0.01176178],
        [0.91041803, 0.641611  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.13778579, 0.29245162],
        [0.91041803, 0.25246203],
        [0.01176178, 0.641611  ]], dtype=float32)>)

#Dot Product
Dot Product is also referred to as Matrix Multiplication

1.   tf.matmul()
2.   tf.tensordot()
3. @


Generally while performing matrix muliplication and if the one of the axes doesn't line up .We will perform tranpose on the tensor rather than reshaping

In [13]:
X=tf.constant([[2,3],[4,5],[6,7]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [6, 7]], dtype=int32)>

In [14]:
Y=tf.constant([[1,2,3],[4,5,6]])
Y


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 19, 24],
       [24, 33, 42],
       [34, 47, 60]], dtype=int32)>

##Changing the Datatype of a Tensor
Use the tf.cast()
tf.cast() return a new tensor and the original tensor remains unchanged.


In [16]:
a=tf.constant([1,2,3])
a.dtype

tf.int32

In [17]:
b=tf.constant([1.5,3.4])
b.dtype

tf.float32

In [18]:
c=tf.constant([[1,1.7]])
c.dtype

tf.float32

In [19]:
tf.cast(c,dtype=tf.int32)


<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 1]], dtype=int32)>

In [20]:
tf.cast(b,dtype=tf.float16)


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.5, 3.4], dtype=float16)>

##Aggregation
Aggregating tensors = condensing them from multiple values to smaller amount of values

In [21]:

x=tf.constant([-1,-2])
x


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [22]:
tf.abs(x)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

Some common aggregation forms:


*   min
*   max
*   sum
*   mean



In [23]:
tf.reduce_sum(x,axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=-3>

In [24]:
rnk_2=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
rnk_2.shape

TensorShape([3, 3])

axis=0 calculates sum vertically and axis =1 calculates sum horizontally

In [25]:
tf.reduce_sum(rnk_2,axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 15, 18], dtype=int32)>

In [26]:
tf.reduce_sum(rnk_2,axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6, 15, 24], dtype=int32)>

If axis is not mentioned all the axis are reduced

In [27]:
tf.reduce_max(rnk_2)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [28]:
tf.reduce_max(rnk_2,axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [29]:
tf.reduce_mean(rnk_2)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

##Variance and Std
variance and std need the math library or the tensorflow probability library


*   math.reduce_variance / math.reduce_std
*   tfp.stats.variance() /tfp.stats.stddev()


Note:math.reduce throws a error if data is in int,where as tfp does not,
for better practice convert to float before applying any operation.



In [30]:
tf.math.reduce_variance(tf.cast(rnk_2,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.666666507720947>

In [31]:
tf.math.reduce_std(tf.cast(rnk_2,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.58198881149292>

By default tfp chooses axis as 1

In [32]:
import tensorflow_probability as tfp
tfp.stats.variance(tf.cast(rnk_2,dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([6., 6., 6.], dtype=float32)>

In [33]:
tfp.stats.variance(tf.cast(rnk_2,dtype=tf.float32),sample_axis=None)


<tf.Tensor: shape=(), dtype=float32, numpy=6.666666507720947>

In [34]:
tfp.stats.stddev(tf.cast(rnk_2,dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.4494896, 2.4494896, 2.4494896], dtype=float32)>

##Finding Postional Minimum and Maximum

In [35]:
tf.random.set_seed(42)
X=tf.random.uniform([50])
X

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [36]:
tf.argmax(X)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [37]:
tf.argmin(X)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

##Squeezing a tensor(removing all single dimensions)

In [38]:
tf.random.set_seed(42)
squeeze =tf.random.uniform(shape=[1,1,100,1,1])
squeeze

<tf.Tensor: shape=(1, 1, 100, 1, 1), dtype=float32, numpy=
array([[[[[0.6645621 ]],

         [[0.44100678]],

         [[0.3528825 ]],

         [[0.46448255]],

         [[0.03366041]],

         [[0.68467236]],

         [[0.74011743]],

         [[0.8724445 ]],

         [[0.22632635]],

         [[0.22319686]],

         [[0.3103881 ]],

         [[0.7223358 ]],

         [[0.13318717]],

         [[0.5480639 ]],

         [[0.5746088 ]],

         [[0.8996835 ]],

         [[0.00946367]],

         [[0.5212307 ]],

         [[0.6345445 ]],

         [[0.1993283 ]],

         [[0.72942245]],

         [[0.54583454]],

         [[0.10756552]],

         [[0.6767061 ]],

         [[0.6602763 ]],

         [[0.33695042]],

         [[0.60141766]],

         [[0.21062577]],

         [[0.8527372 ]],

         [[0.44062173]],

         [[0.9485276 ]],

         [[0.23752594]],

         [[0.81179297]],

         [[0.5263394 ]],

         [[0.494308  ]],

         [[0.21612847]],

     

In [39]:
tf.squeeze(squeeze).shape

TensorShape([100])

##One hot Encoding Tensors

In [40]:
list=[1,2,3]
tf.one_hot(list,depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [41]:
tf.one_hot(list,depth=3,on_value="yo",off_value="no")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'no', b'yo', b'no'],
       [b'no', b'no', b'yo'],
       [b'no', b'no', b'no']], dtype=object)>

##Square Log and SquareRoot

In [42]:
A=tf.range(1,10)
A

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [43]:
tf.math.square(A)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [44]:
tf.math.sqrt(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [45]:
tf.math.log(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

In [46]:
#creating a tensor from an numpy array
import numpy as np
E=tf.constant(np.array([1.,2,3,5,6]))
E

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 5., 6.])>

In [47]:
#converting tensor to numpy array
np.array(E)

array([1., 2., 3., 5., 6.])

In [48]:
E.numpy()

array([1., 2., 3., 5., 6.])

Creating a tensor using numpy array give float64 whereaas creating tesnor with normal python list give float32

In [49]:
G=tf.constant([1.,2.,3.])
F=tf.constant(np.array([1.,2.,3.]))
G.dtype ,F.dtype

(tf.float32, tf.float64)

##Access to GPU's

In [50]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [51]:
!nvidia-smi

Sun Jun  1 16:59:26 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   67C    P0             29W /   70W |     106MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Note: If you have a CUDA enabled GPU,Tensorflow will automatically use it whenever possible