<a href="https://colab.research.google.com/github/Ashwin-2408/Tensor_Flow_Learning/blob/main/notebooks/TensorFlowBasics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Manipulating Tensors
Basics Operations:


*  +
*  -
*   *
*  /



In [2]:
import tensorflow as tf
A=tf.constant([2,2])

In [3]:
A+10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 12], dtype=int32)>

It does not change the original tensor

In [4]:
A


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

Use Tensorflow builtin functions to speed up operations while training

In [8]:
tf.multiply(A,4)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 8], dtype=int32)>

##Matrix Multiplication
Matrix multiplication is the most common operation in Machine Learning

In [19]:
A=tf.constant([[1,3]], shape=[1,2])
B=tf.constant([[2,4]],shape=[2,1])
A,B

(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[2],
        [4]], dtype=int32)>)

The number of columns in the first tensor should be equal to the number of rows in the second tensor

In [20]:
tf.linalg.matmul(A,B)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [25]:
C=tf.constant([[1,2,3],[3,4,5],[5,6,5]])
C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 5]], dtype=int32)>

Element wise Multiplication

In [26]:
C*C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [ 9, 16, 25],
       [25, 36, 25]], dtype=int32)>

The '@' operator in python if for matrix multiplication

In [27]:
C@C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 28, 28],
       [40, 52, 54],
       [48, 64, 70]], dtype=int32)>